# Generated by Django 4.2.7 on 2025-04-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0056_alter_collectorsession_ingestor_type_and_more'),
        ('dcas', '0009_dcasmessagepriority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcaserrorlog',
            name='farm',
        ),
        migrations.AddField(
            model_name='dcaserrorlog',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data related to the error.', null=True),
        ),
        migrations.AddField(
            model_name='dcaserrorlog',
            name='farm_registry',
            field=models.ForeignKey(blank=True, help_text='The unique identifier of the farm that failed to process.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gap.farmregistry'),
        ),
        migrations.AddField(
            model_name='dcaserrorlog',
            name='messages',
            field=models.JSONField(blank=True, default=list, help_text='List of output message codes.', null=True),
        ),
        migrations.AlterField(
            model_name='dcaserrorlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Details about why the farm could not be processed.', null=True),
        ),
        migrations.AlterField(
            model_name='dcaserrorlog',
            name='error_type',
            field=models.CharField(choices=[('MISSING_MESSAGES', 'Missing Messages'), ('PROCESSING_FAILURE', 'Processing Failure'), ('FOUND_REPETITIVE', 'Found Repetitive'), ('OTHER', 'Other')], default='OTHER', help_text='The type of error encountered.', max_length=50),
        ),
    ]
